import React from "react";
import Head from "next/head";
import { Inter } from "@next/font/google";
import { useUser, useSupabaseClient } from "@supabase/auth-helpers-react";
import { useQuery } from "@tanstack/react-query";
import { queryKeys } from "@/lib/react-query";
import { createServerSupabaseClient } from "@supabase/auth-helpers-nextjs";
import { GetServerSideProps } from "next";
import { AccountsApi } from "@/lib/supabase/api";

const inter = Inter({ subsets: ["latin"] });

interface Props {
  accounts: Awaited<ReturnType<typeof AccountsApi.getMany>>;
}

export default function Home({ accounts }: Props) {
  const user = useUser();
  const supabase = useSupabaseClient();
  const accountsQuery = useQuery(
    queryKeys.accounts,
    () => AccountsApi.getMany(supabase),
    {
      initialData: accounts,
      staleTime: 1000 * 60 * 60,
    }
  );

  React.useEffect(() => {
    supabase.auth.signInWithPassword({
      email: "fokof17465@cnxcoin.com",
      password: "Admin.1234",
    });
  }, [supabase.auth]);

  if (!user) return <div>Not logged in</div>;

  return (
    <>
      <Head>
        <title>Money App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <h1>Welcome to Next.js!</h1>

        <ul>
          {accountsQuery.data?.map((account) => (
            <li key={account.id}>{account.title}</li>
          ))}
        </ul>
      </main>
    </>
  );
}

export const getServerSideProps: GetServerSideProps<Props> = async (
  context
) => {
  const supabase = createServerSupabaseClient(context);
  const accounts = await AccountsApi.getMany(supabase);

  return {
    props: {
      accounts: accounts ?? [],
    },
  };
};
